# Generated by Django 5.0.2 on 2024-02-24 09:08

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('dob', models.DateField(blank=True, null=True)),
                ('pob', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=20)),
                ('country', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('resident', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('verification_code', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='email')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.Users.update_filename)),
                ('language', models.CharField(choices=[('en', 'english'), ('fr', 'french')], default='en', max_length=10)),
                ('verified_on', models.DateTimeField(null=True, verbose_name='emailed verification date')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('stars', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user setting',
                'verbose_name_plural': 'users settings',
                'db_table': 'users_settings',
            },
        ),
        migrations.CreateModel(
            name='ValidationCodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('reset_code', models.TextField(max_length=6, verbose_name='reset code')),
                ('code_for', models.CharField(choices=[('PWR', 'Password Reset code'), ('PNV', 'Phone NUmber Validation'), ('UVC', 'User verification Code')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation Code',
                'verbose_name_plural': 'Validation Codes',
                'db_table': 'validation_codes',
            },
        ),
    ]
