# Generated by Django 4.2.6 on 2023-10-26 16:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'user setting', 'verbose_name_plural': 'users settings'},
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
