# Generated by Django 4.2.7 on 2023-12-04 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_en',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='role_fr',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
