# Generated by Django 4.2.7 on 2023-12-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_role_alter_role_role_en_alter_role_role_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.AddField(
            model_name='users',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
