# Generated by Django 4.2.6 on 2023-10-26 17:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
