# Generated by Django 4.2.6 on 2023-10-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
