# Generated by Django 4.2.7 on 2023-11-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
