# Generated by Django 4.2.6 on 2023-12-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_gift_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='img',
            field=models.ImageField(default=1, upload_to='gifts/'),
            preserve_default=False,
        ),
    ]
