# Generated by Django 4.2.6 on 2024-01-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_giftrequest_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrequest',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gifts.giftrequest'),
        ),
    ]
