# Generated by Django 4.2.6 on 2024-03-14 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('Taxpayer_number', models.CharField(max_length=255, unique=True)),
                ('branch', models.CharField(max_length=255)),
                ('big_branch', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('agent', models.CharField(max_length=255)),
                ('date_create', models.DateField()),
                ('effect_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Police_number', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
