# Generated by Django 4.2.6 on 2024-03-11 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_product_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='canceled_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_conceled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceduration',
            name='duration_unit',
            field=models.CharField(choices=[('WEK', 'Weeks'), ('MON', 'Months'), ('YEA', 'Year')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agerange',
            name='above',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agerange',
            name='below',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
