# Generated by Django 4.2.6 on 2024-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_contract_canceled_at_contract_canceled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonecover',
            name='zone_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='zonecover',
            name='zone_fr',
            field=models.CharField(max_length=200),
        ),
    ]
