# Generated by Django 4.2.6 on 2024-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_zonecover_zone_en_alter_zonecover_zone_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='direct_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
