# Generated by Django 4.2.6 on 2024-03-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_product_zone_covered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='zone_covered',
        ),
    ]
