# Generated by Django 4.2.6 on 2024-03-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_product_zone_covered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zone_covered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='services.zonecover'),
        ),
    ]
