# Generated by Django 4.2.6 on 2024-03-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_product_image_alter_product_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='services/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(upload_to='services/logos/'),
        ),
    ]
