# Generated by Django 4.2.7 on 2023-11-28 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('question_en', models.TextField()),
                ('question_fr', models.TextField()),
                ('answer_en', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
