# Generated by Django 4.2.7 on 2023-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
